FROM alpine:3.7

# environment variables
ENV TERM=xterm

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache  \
	bash \
	git \
	maven \
	openjdk8 && \
 echo "**** clone source ****" && \
 git clone git://github.com/Libresonic/libresonic.git /usr/src/libresonic && \
 git -C /usr/src/libresonic checkout $(git -C /usr/src/libresonic describe --tags --candidates=1 --abbrev=0) && \
 cd /usr/src/libresonic && \
 echo "**** build war file ****" && \
 mvn package && \
 echo "**** copy war file to output folder ****" && \
 mkdir -p \
	/package && \
 cp /usr/src/libresonic/libresonic-main/target/libresonic.war /package && \
 chmod -R 777 /package

# copy war file out to mounted directory
CMD ["cp", "-avr", "/package", "/mnt/"]
