FROM alpine:3.4
MAINTAINER sparklyballs

# environment variables
ENV TERM=xterm

# install packages
RUN \
 apk add --no-cache  \
	bash \
	git \
	openjdk8 && \
 apk add --no-cache \
	--repository http://nl.alpinelinux.org/alpine/edge/community \
	maven

# clone source
RUN \
 git clone git://github.com/Libresonic/libresonic.git /usr/src/libresonic && \
 git -C /usr/src/libresonic checkout $(git -C /usr/src/libresonic describe --tags --candidates=1 --abbrev=0) && \
 cd /usr/src/libresonic && \

# build war file
 mvn package

# copy war file to output folder
RUN \
 mkdir -p \
	/package && \
 cp /usr/src/libresonic/libresonic-main/target/libresonic.war /package

# Copy war file out to mounted directory
CMD ["cp", "-avr", "/package", "/mnt/"]
