#!/usr/bin/with-contenv bash


cd "${LIBRE_HOME}"

s6-setuidgid abc \
java -Dlibresonic.home="${LIBRE_SETTINGS}" \
-Dlibresonic.defaultMusicFolder=/music \
-Dlibresonic.defaultPodcastFolder=/podcasts \
-Dlibresonic.defaultPlaylistFolder=/playlists \
-jar /usr/share/java/jetty-runner.jar \
libresonic.war
