#!/usr/bin/with-contenv bash

mkdir -p "${LIBRE_SETTINGS}"/transcode

if [[ ! -e "${LIBRE_SETTINGS}"/transcode/ffmpeg || ! -e  "${LIBRE_SETTINGS}"/transcode/flac || ! -e "${LIBRE_SETTINGS}"/transcode/lame  ]]; then
ln -sf /usr/bin/ffmpeg "${LIBRE_SETTINGS}"/transcode/
ln -sf /usr/bin/flac "${LIBRE_SETTINGS}"/transcode/
ln -sf /usr/bin/lame "${LIBRE_SETTINGS}"/transcode/
fi

chown abc:abc /media /music /playlists /podcasts

chown -R abc:abc /config "${LIBRE_SETTINGS}"  "${LIBRE_HOME}"
